/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function asyncFibonacci(arg: number): Promise<number>

export declare function fibonacci(n: number): number

export declare function multiThreadedFibonacci(arg: number): Array<number>

export declare function readFileAsync(path: string): Promise<Buffer>

export declare function sum(a: number, b: number): number
